### ISSUE TITLE
optional extraexons

### ISSUE THREAD

**Issue by fedemantica** [biocorecrg/ExOrthist#24]
When the parameter "extraexons" is provided,  the main.nf expects additional exons for all the species.
It would be ideal to make this input file optional, so that it could be provided only for a subset of species.

**Comment by lucacozzuto** [comment]
I'm trying to fix it but for double-checking I would need some extra exon for the test dataset. Can you provide me one, please? Just a dummy example so that I can make tests

**Comment by lucacozzuto** [comment]
Fixed at https://github.com/biocorecrg/ExOrthist/commit/26bd11539efa528da877bd51947198f118988e15
