### ISSUE TITLE
It seems that ExOrthist can only installed somewhere under /home/

### ISSUE THREAD

**Issue by ttbond** [biocorecrg/ExOrthist#26]
Hi~

I cloned ExOrthist into two different directory. One is under /home/ and the other not. But when I run the test commands, the one under /home/ succeeded while the other one exit with the following error information 
`/bin/bash: line 0: cd: /pathTo/ExOrthist/work/35/f33cfb16438043eafd741b9b0f7f58: No such file or directory
/bin/bash: /pathTo/ExOrthist/work/35/f33cfb16438043eafd741b9b0f7f58/.command.sh: No such file or directory`.

**Comment by lucacozzuto** [comment]
Hi, which container are you using? Can you write your command line, please?

**Comment by ttbond** [comment]
The command is `nextflow run main.nf -with-singularity -bg > log.txt`.

**Comment by lucacozzuto** [comment]
It looks like is not able to reach that folder (like missing privileges or volume not mounted). You can also try to add this string of code to the nextflow.config file:

```
singularity.autoMounts = true
```

**Comment by mirimia** [comment]
Hi @ttbond, 

Could I close this issue? 

BTW, we're releasing a new version soon. 

Cheers
Manu

**Comment by ttbond** [comment]
Thanks for the help and sorry for forgetting to close the issue.
