### ISSUE TITLE
Illegal division by zero at B3_realign_EX_pairs.pl line 276.

### ISSUE THREAD

**Issue by suyeonwy** [biocorecrg/ExOrthist#32]
Hi,

I'm trying to run ExOrthist for identifying a set of orthologous exons in human, pig, and mouse.

After the 'parse_IPA_prot_aln' step, several 'realign_EX_pairs' are successfully done.
However, I got the following error in one submitted 'realing_EX_pairs' process.
```
Error executing process > 'realign_EX_pairs (255)'

Caused by:
  Process `realign_EX_pairs (255)` terminated with an error exit status (255)

Command executed:

  B3_realign_EX_pairs.pl hg38 susScr11 hg38-susScr11_EXs_to_realign_part_76_1.txt hg38/hg38.exint susScr11/susScr11.exint 1 realigned_hg38-susScr11_EXs_to_realign_part_76_1.txt  hg38_susScr11 blosum62

Command exit status:
  255

Command output:
  hg38_susScr11/tex_part_1.exint
  hg38_susScr11/tex_part_1.gde

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Illegal division by zero at /mss/projects/RDA/minipig_exon/ExOrthist/bin/B3_realign_EX_pairs.pl line 276.

```

And I found that the $m1 value in score_proteins function in B3_realign_EX_pairs.pl became zero after the loop statement for scoring proteins.
The $m1 value was calculated using $sc{'XX'} + $sc{'XX'} + $sc{'XX'} + $sc{'XX'} + $sc{'VV'} = (-1) + (-1) + (-1) + (-1) + 4 = 0.
```
##scoring proteins
    for ($i=0; $i<scalar(@s1); $i++){
        if ($sc{$s1[$i].$s2[$i]}){
            $e_score+=$sc{$s1[$i].$s2[$i]};
        }
        if ($s1[$i] eq $s2[$i]){
            $id_score++;
            $sim_score++;
            $ng=0;
        }
        elsif ($sim{$s1[$i].$s2[$i]}){
            $sim_score++;
            $ng=0;
        }
        elsif ($s2[$i] eq "-" || $s1[$i] eq "-") { if ($ng==0) { $g++; $ng=1; } else { $e++; $ng=1;} }
        **if ($sc{$s1[$i].$s1[$i]}) { $m1+=$sc{$s1[$i].$s1[$i]}; }**
        if ($sc{$s2[$i].$s2[$i]}) { $m2+=$sc{$s2[$i].$s2[$i]}; }
    }
```
I considered about changing the BLOSUM62 matrix used for scoring, but there is always a possibility that the m1 or m2 value becomes zero. 
Could you please check the issue?

Thank you!

**Comment by fedemantica** [comment]
Hello,

Can you please check if you have pulled the latest modifications to the B3 script? Another user had the same issue, but we should have fixed it ~10 days ago. If your problem persists,  please let us know! We will look into it again!

Best,
Fede

**Comment by suyeonwy** [comment]
Hi,

I got the final result without any errors after getting the latest version of the script!

Thanks!
