### ISSUE TITLE
Error executing process > 'split_EX_pairs_to_realign (1)'

### ISSUE THREAD

**Issue by vanesroy** [biocorecrg/ExOrthist#36]
Hi all,

I keep getting this error while trying to run ExOrthist:

  Error executing process > 'split_EX_pairs_to_realign (1)'
  
  Caused by:
  
    Process `split_EX_pairs_to_realign` input file name collision -- There are multiple input files for each of the following file names: gallus_gallus-xenopus_tropicalis_EXs_to_split_part_gallus-xenopus.txt, alligator_sinensis-gallus_gallus_EXs_to_split_part_sinensis-gallus.txt, alligator_sinensis-xenopus_tropicalis_EXs_to_split_part_sinensis-xenopus.txt

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

I don't know how to solve this issue. Could you please give me some pointers as to how to solve this?

Many thanks,
Vanessa

**Comment by vanesroy** [comment]
Hi Fede,

Sure, here is my params.config file, and below the names of the gtf and genome fasta files, and the content of the evodists.txt file. 

---
**Params file:**

  params {
      cluster        = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/3_orgs_newtry/other/orthogroups_input_exorthist.tab"
      genomes        = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/3_orgs_newtry/genomes/*_gDNA.fasta"
      annotations    = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/3_orgs_newtry/annotations/*_annot.gtf"
      alignmentnum   = 1000
      orthogroupnum  = 500
      extraexons     = ""
      bonafide_pairs = ""
      orthopairs     = ""
      evodists       = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/3_orgs_newtry/other/evodist.tsv"
      long_dist      = "2,0.10,0.40,0.15"
      medium_dist    = "2,0.30,0.60,0.20"
      short_dist     = "2,0.50,0.60,0.25"
      prevaln        = ""
      output         = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/output/exorthist/newtry4_output_test_3_organisms_24May2023/"
      email          = ""
  }

---
**Name of genome fasta files:**
directory_name: /splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/3_orgs_newtry/genomes/

alligator_sinensis_gDNA.fasta
gallus_gallus_gDNA.fasta
xenopus_tropicalis_gDNA.fasta

**Name of gtf files:**
directory_name: /splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/3_orgs_newtry/annotations/

alligator_sinensis_annot.gtf
gallus_gallus_annot.gtf
xenopus_tropicalis_annot.gtf

---

**evodist.tsv**

gallus_gallus	alligator_sinensis	medium
gallus_gallus	xenopus_tropicalis	medium
alligator_sinensis	xenopus_tropicalis	medium


---


Many thanks for your help!

Best
Vanessa

**Comment by fedemantica** [comment]
Hi Vanessa,

Can I ask you to check/try a couple of things?

**1.** This is our fault, because we need to update the README. One user had problems because he had underscores in the species identifier (as you also have). Could you try to run it by changing these species identifier? E.g. gallus_gallus as ggallus, xenopus_tropicalis as xtropicalis etc
**2.**  Could you please double-check that the species identifiers in **orthogroups_input_exorthist.tab** correspond to the files' ones? I'm sure they do, but just in case!

Please let me know if this fixes your issue or if you still get error messages.
Thanks,
Fede

**Comment by vanesroy** [comment]
Hi Fede

Changing the species names to ones without underscores worked. Amazing, thanks a lot for your help!

Best,
Vanessa
