### ISSUE TITLE
Running ExOrthist with mus musculus file gives an error

### ISSUE THREAD

**Issue by vanesroy** [biocorecrg/ExOrthist#37]
Hi,

I am trying to run ExOrthist with five organisms (homo_sapiens, mus_musculus, gallus_gallus, alligator_sinensis, xenopus_tropicalis). 

But somehow, I keep getting the following error, and I can't figure out why:

Error executing process > 'generate_annotations (mmusculus)'

Caused by:
  Process `generate_annotations (mmusculus)` terminated with an error exit status (137)

Command executed:

  A1_generate_annotations.pl -GTF mmusculus_annot.gtf -G mmusculus_gDNA.fasta -sp mmusculus

Command exit status:
  137

Command output:
  (empty)

Command error:
  [ExOrthist annotation]: EXONS_DB path set to /storage/apps/ExOrthist/ExOrthist/work/10/4b1a4983f4fef5b7d4f54e45ff5e97
  [ExOrthist annotation]: Parsing gDNA file for mmusculus
  .command.sh: line 2:     8 Killed                  A1_generate_annotations.pl -GTF mmusculus_annot.gtf -G mmusculus_gDNA.fasta -sp musculus

---
This is my params.config file:

params {
    cluster        = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/NEWTRY_31May2023_5_orgs/other/orthogroups_input_exorthist_5orgs_31May2023_final.tab"
    genomes        = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/NEWTRY_31May2023_5_orgs/genomes/\*_gDNA.fasta"
    annotations    = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/NEWTRY_31May2023_5_orgs/annotations/\*_annot.gtf"
    alignmentnum   = 1000
    orthogroupnum  = 500
    extraexons     = ""
    bonafide_pairs = ""
    orthopairs     = ""
    evodists       = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/data/exorthist/NEWTRY_31May2023_5_orgs/other/evodists.txt"
    long_dist      = "2,0.10,0.40,0.15"
    medium_dist    = "2,0.30,0.60,0.20"
    short_dist     = "2,0.50,0.60,0.25"
    prevaln        = ""
    output         = "/splice-jbod/vanessaroy/projects/AS_Evo_3D/data_processing/output/exorthist/NEWTRY_output_test_5_organisms_31May2023/"
    email          = ""
}

---

Any pointers on how to fix this issue would be greatly appreciated.

It's strange, because the gtf and fasta files I downloaded for mus_musculus and homo_sapiens are from Ensembl. 
When I ran ExOrthist with three organisms (gallus_gallus, alligator_sinensis, xenopus_tropicalis), it worked, and gallus_gallus and xenopus_tropicalis gtf and fasta files are from Ensembl as well.

Also, I am not using underscores in the file names / species names.

Many thanks,
Vanessa

**Comment by mirimia** [comment]
Hello,

Is it possible you made a mistake with the species names? Here it says musculus (not mmusculus):

.command.sh: line 2: 8 Killed A1_generate_annotations.pl -GTF mmusculus_annot.gtf -G mmusculus_gDNA.fasta -sp musculus

Otherwise I'll take another look, but as you say, ensembl files should all be the same.

M

**Comment by fedemantica** [comment]
Hi Vanessa,

I think it might be a memory problem... Can you please try to change the memory specification in the **nextflow.config** file?
You have to look for the memory specification in the general process section, hopefully changing it from 4.5G to 8G should be enough:

```
process {
    containerOptions = { workflow.containerEngine == "docker" ? '-e USER=$USER -e HOME=$HOME -u $(id -u):$(id -g)': null}
    queue = 'long-sl7,short-sl7'
    cache = 'lenient'
    memory='4.5G'
    cpus='1'
    time='6h'
    scratch = false
    containerOptions = { workflow.containerEngine == "docker" ? '-u $(id -u):$(id -g)': null}
```

Could you please give it a go and let me know if it works? Otherwise I think we can change the label for that process.
Thanks a lot!
Fede
