### ISSUE TITLE
Error in my ExOrthist run 

### ISSUE THREAD

**Issue by LudoCrg** [biocorecrg/ExOrthist#38]
Hello,

I have been unable to complete my ExOrthist run because of the following error:

ERROR  : Unknown image format/type: /nfs/users/lserrano/lciampi/JuanRamon/Orthologies/ExOrthist/singularity/biocorecrg-exon_intron_pipe-0.2.img
ABORT  : Retval = 255

I have been using nextflow version 20.04.1 (as recommended in the README) and singularity version 3.8.3, running the following command:
NXF_VER=20.04.1 nextflow run [main.nf](http://main.nf/) -with-singularity

Could you please help me figure out what the problem is? Of course, let me know if you need any other information.

Thanks a lot in advance!

**Comment by lucacozzuto** [comment]
Hi, can you check the version of singularity is the same in the main node and in the cluster nodes? This seems like a mismatch between the versions. If you are using modules is better to put the load command in the .bashrc
